job('First-Maven-Project-Via-DSL') {
    description("Version-2-First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/clarusway-aws-devops/java-tomcat-sample-main.git", 'main')
    }
    triggers {
        scm('* H * * *')
    }
    steps {
        maven{
            goals('clean package')
            rootPOM('pom.xml')
            mavenInstallation('maven-3.9.9')
        }
    }
    // publishers {
    //     //archive the war file generated
    //     archiveArtifacts '**/*.jar'
    // }
}
